export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'; 
export const REMOVE_APP_FROM_HOST = 'REMOVE_APP_FROM_HOST';
export const ADD_APP_TO_HOSTS = 'ADD_APP_TO_HOSTS';
export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';
